"""big migration

Revision ID: 1d421979ce01
Revises: 7a76090f5d97
Create Date: 2024-04-23 13:53:12.858173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d421979ce01'
down_revision = '7a76090f5d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('added')
        batch_op.drop_column('last_sync')

    with op.batch_alter_table('user_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('added')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('added_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('synced_at')
        batch_op.drop_column('added_at')

    # ### end Alembic commands ###
