"""Initial migration.

Revision ID: 7a76090f5d97
Revises: 0159c9ad8ec4
Create Date: 2024-04-23 01:42:34.450759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a76090f5d97'
down_revision = '0159c9ad8ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_sync', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('user_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added', sa.DateTime(), nullable=True))
        batch_op.drop_column('added_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('added')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_sync')
        batch_op.drop_column('added')

    # ### end Alembic commands ###
