"""Ini2332

Revision ID: a537c7ffee77
Revises: 4e4d47afae73
Create Date: 2024-04-20 02:59:16.063277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a537c7ffee77'
down_revision = '4e4d47afae73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movie', schema=None) as batch_op:
        batch_op.alter_column('added_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movie', schema=None) as batch_op:
        batch_op.alter_column('added_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
